# This is the final blueprint for a Docker deployment in a sub-directory.

services:
  # This section defines our Java backend API.
  - type: web
    name: zoha-api
    # Tell Render to use a Docker environment.
    env: docker
    
    # --- THIS IS THE FIX ---
    # We define a 'dockerContext' which tells Docker to 'cd' into this directory first.
    dockerContext: ./ArchitectureWebsite
    # Then, we tell it the name of the Dockerfile *within that context*.
    dockerfilePath: ./Dockerfile
    
    # Specify the free instance type.
    plan: free
    # Define our environment variables.
    envVars:
      - key: spring.datasource.url
        value: jdbc:mysql://YOUR_RAILWAY_HOST:YOUR_RAILWAY_PORT/YOUR_RAILWAY_DATABASE_NAME
      - key: spring.datasource.username
        value: root
      - key: spring.datasource.password
        value: YOUR_RAILWAY_PASSWORD_PLACEHOLDER
      - key: spring.jpa.hibernate.ddl-auto
        value: update