# Simplified and corrected Render blueprint for Docker.

services:
  - type: web
    name: zoha-api
    env: docker
    # We point directly to the Dockerfile's location from the root.
    # We are REMOVING the dockerContext line.
    dockerfilePath: ./ArchitectureWebsite/Dockerfile
    plan: free
    envVars:
      - key: spring.datasource.url
        value: jdbc:mysql://YOUR_RAILWAY_HOST:YOUR_RAILWAY_PORT/YOUR_RAILWAY_DATABASE_NAME
      - key: spring.datasource.username
        value: root
      - key: spring.datasource.password
        value: YOUR_RAILWAY_PASSWORD_PLACEHOLDER
      - key: spring.jpa.hibernate.ddl-auto
        value: update