# This is the most robust version of the Render blueprint.

services:
  # This section defines our Java backend API.
  - type: web
    name: zoha-api
    # This is the most explicit way to define the environment.
    # It tells Render to use its native environment for Java 17.
    env: docker
    dockerfile: Dockerfile
    # Tell Render where the code is.
    rootDir: ./ArchitectureWebsite
    # Define the build and start commands.
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/portfolio-api-*.jar"
    # Specify the free instance type.
    plan: free
    # Define our environment variables.
    envVars:
      - key: spring.datasource.url
        value: jdbc:mysql://YOUR_RAILWAY_HOST:YOUR_RAILWAY_PORT/YOUR_RAILWAY_DATABASE_NAME
      - key: spring.datasource.username
        value: root
      - key: spring.datasource.password
        value: YOUR_RAILWAY_PASSWORD_PLACEHOLDER
      - key: spring.jpa.hibernate.ddl-auto
        value: update