# This blueprint tells Render how to run our pre-compiled Java application.

services:
  # This section defines our Java backend API.
  - type: web
    name: zoha-api
    # This explicitly sets the environment to Java.
    env: java
    # Tell Render where our Java project is located.
    rootDir: ./ArchitectureWebsite
    
    # --- THIS IS THE KEY ---
    # The build command is empty because we have already built the JAR.
    buildCommand: ""
    # The start command tells Render how to run our pre-compiled JAR.
    startCommand: "java -jar target/ArchitectureWebsite-0.0.1-SNAPSHOT.jar"
    
    plan: free
    envVars:
      - key: spring.datasource.url
        value: jdbc:mysql://YOUR_RAILWAY_HOST:YOUR_RAILWAY_PORT/YOUR_RAILWAY_DATABASE_NAME
      - key: spring.datasource.username
        value: root
      - key: spring.datasource.password
        value: YOUR_RAILWAY_PASSWORD_PLACEHOLDER
      - key: spring.jpa.hibernate.ddl-auto
        value: update