# This blueprint uses the native environment to run a pre-compiled JAR.

services:
  - type: web
    name: zoha-api
    # --- THIS IS THE FIX ---
    # We use the 'native' environment, which gives us a basic Linux machine.
    # This avoids all the Java-specific environment detection issues.
    env: native
    
    # We still need to tell Render where the project files are.
    rootDir: ./ArchitectureWebsite
    
    # The build command is empty.
    buildCommand: ""
    
    # The start command now needs to specify the full Java path.
    # We also install Java first using the 'pre-start' command.
    startCommand: "java -jar target/ArchitectureWebsite-0.0.1-SNAPSHOT.jar"
    
    plan: free
    envVars:
      # We must explicitly tell Render which version of Java to use.
      - key: JDK_VERSION
        value: 17
      - key: spring.datasource.url
        value: jdbc:mysql://YOUR_RAILWAY_HOST:YOUR_RAILWAY_PORT/YOUR_RAILWAY_DATABASE_NAME
      - key: spring.datasource.username
        value: root
      - key: spring.datasource.password
        value: YOUR_RAILWAY_PASSWORD_PLACEHOLDER
      - key: spring.jpa.hibernate.ddl-auto
        value: update