# This file is an instruction manual for Render.
# It defines all the services in our project.

services:
  # This section defines our Java backend API.
  - type: web
    name: zoha-api
    env: java 
    # THIS IS THE FIX: Changed to match your actual folder name.
    rootDir: ./ArchitectureWebsite
    # Define the build and start commands.
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/portfolio-api-*.jar"
    # Specify the free instance type.
    plan: free
    # This section is for our database credentials.
    # You will add your Railway database details here on the Render website.
    envVars:
      - key: spring.datasource.url
        # This will be a placeholder. We will set the real value in Render's UI.
        value: jdbc:mysql://YOUR_RAILWAY_HOST:YOUR_RAILWAY_PORT/YOUR_RAILWAY_DATABASE_NAME
      - key: spring.datasource.username
        value: root
      - key: spring.datasource.password
        # We will set this secret value in Render's UI.
        fromSecret: true
      - key: spring.jpa.hibernate.ddl-auto
        value: update