# This blueprint uses the correct `runtime` keyword for a native environment.

services:
  - type: web
    name: zoha-api
    
    # --- THIS IS THE FIX ---
    # The correct keyword is `runtime`. My apologies.
    runtime: native
    
    # Tell Render where our project files are located.
    rootDir: ./ArchitectureWebsite
    
    # The build command is empty because the JAR is pre-compiled.
    buildCommand: ""
    
    # The command to run our application.
    startCommand: "java -jar target/ArchitectureWebsite-0.0.1-SNAPSHOT.jar"
    
    plan: free
    envVars:
      # We must explicitly tell Render which version of Java to make available.
      - key: JDK_VERSION
        value: 17
      - key: spring.datasource.url
        value: jdbc:mysql://YOUR_RAILWAY_HOST:YOUR_RAILWAY_PORT/YOUR_RAILWAY_DATABASE_NAME
      - key: spring.datasource.username
        value: root
      - key: spring.datasource.password
        value: YOUR_RAILWAY_PASSWORD_PLACEHOLDER
      - key: spring.jpa.hibernate.ddl-auto
        value: update